<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Privacy Policy - Aliox Player</title>
  <style>
    :root {
      color-scheme: light dark;
      --background: #ffffff;
      --foreground: #111111;
      --muted: #555555;
      --border: #dddddd;
      --link: #0f62fe;
    }

    @media (prefers-color-scheme: dark) {
      :root {
        --background: #0b0b0b;
        --foreground: #f5f5f5;
        --muted: #b8b8b8;
        --border: #2a2a2a;
        --link: #78a9ff;
      }
    }

    body {
      margin: 0;
      background: var(--background);
      color: var(--foreground);
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      line-height: 1.6;
    }

    main {
      width: min(920px, calc(100% - 40px));
      margin: 0 auto;
      padding: 48px 0 64px;
    }

    h1 {
      margin: 0 0 8px;
      font-size: clamp(2rem, 4vw, 3rem);
      line-height: 1.15;
    }

    h2 {
      margin: 40px 0 12px;
      padding-top: 8px;
      border-top: 1px solid var(--border);
      font-size: 1.35rem;
      line-height: 1.3;
    }

    p,
    li {
      font-size: 1rem;
    }

    .updated {
      margin: 0 0 32px;
      color: var(--muted);
      font-weight: 600;
    }

    a {
      color: var(--link);
    }

    code {
      padding: 0.12em 0.35em;
      border-radius: 4px;
      background: color-mix(in srgb, var(--foreground) 10%, transparent);
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
      font-size: 0.95em;
    }
  </style>
</head>
<body>
  <main>
    <h1>Privacy Policy - Aliox Player</h1>
    <p class="updated">Last Updated: August 11, 2026</p>

    <p><strong>Aliox Player</strong> ("the app", "we", "our") respects your privacy. This Privacy Policy explains what information the app accesses, why that information is used, and how you can remove local information generated by the app.</p>

    <h2>1. Scope of This Policy</h2>
    <p>Aliox Player is a music player for Android. The app can play local files from your device and, when you choose to connect an account or server, can also access music stored in compatible cloud services such as <strong>Microsoft OneDrive</strong>, WebDAV, and FTPS.</p>
    <p>The app does not operate a remote Aliox server for your music library, playlists, favorites, offline downloads, Private Top 10 Stats, or local backup files.</p>

    <h2>2. Information the App Accesses</h2>
    <p>Aliox Player accesses only the information required to build your library and play your music:</p>
    <ul>
      <li><strong>File metadata</strong>: file names, identifiers, sizes, file types, folder structure, artist, album, track title, track number, and cover art when available.</li>
      <li><strong>Audio content</strong>: music files read for playback, offline download, or metadata extraction.</li>
      <li><strong>Local library data</strong>: library index, playlists, favorites, cached artwork, technical sync history, and files downloaded for offline use inside the app.</li>
      <li><strong>Private Top 10 Stats</strong>, if you enable the feature in Settings: local play counts used to show your top 10 songs and albums inside the app.</li>
      <li><strong>Manual backup files</strong>, if you choose to create one: selected app organization data such as liked songs, playlists, and Private Top 10 Stats, plus track references and music metadata needed to restore them.</li>
      <li><strong>Access credentials</strong>: authentication tokens stored locally in encrypted app private storage when supported by the Android version on your device.</li>
      <li><strong>WebDAV connection data</strong>, when configured: server URL and credentials provided by you to access your own server, Nextcloud, ownCloud, or compatible service.</li>
      <li><strong>FTPS connection data</strong>, when configured: server address, port, username, password, and remote paths provided by you to access your server.</li>
    </ul>

    <h2>3. Use of Microsoft OneDrive</h2>
    <p>When you connect OneDrive, sign-in is handled through the Microsoft identity platform. Aliox Player requests only <code>Files.Read</code> and <code>offline_access</code>:</p>
    <ul>
      <li><code>Files.Read</code> lets the app list and read files and folders in your OneDrive so it can identify audio and artwork, play music, and download tracks for offline playback when you request it;</li>
      <li><code>offline_access</code> lets the app refresh the connection without asking you to sign in again each time.</li>
    </ul>
    <p>The app uses read access for your OneDrive library. It is not designed to sell, share, publish, modify, or delete files from your OneDrive.</p>
    <p>Your use of OneDrive is also subject to the Microsoft Privacy Statement: <a href="https://www.microsoft.com/privacy/privacystatement" rel="noopener noreferrer">https://www.microsoft.com/privacy/privacystatement</a>.</p>

    <h2>4. How We Use Information</h2>
    <p>Information accessed by the app is used to:</p>
    <ul>
      <li>display your music library inside the app;</li>
      <li>play local audio files, OneDrive files, or files from connected WebDAV or FTPS servers;</li>
      <li>organize your library by artists, albums, playlists, and other views;</li>
      <li>count completed plays locally when Private Top 10 Stats is enabled;</li>
      <li>create or import a manual backup file when you request it;</li>
      <li>extract and display metadata and artwork;</li>
      <li>enable offline playback for files you choose to download;</li>
      <li>keep the player experience stable in the background.</li>
    </ul>

    <h2>5. Data Sharing</h2>
    <p><strong>We do not sell your data or upload your music library to a remote Aliox-operated server.</strong></p>
    <p>Metadata, playlists, favorites, downloaded files, and Private Top 10 Stats remain on your device, in the app's private storage. Private Top 10 Stats is not sent to any server. Manual backup files are created only when you request them and are saved to the folder you choose. The app does not send backup files to any server. Authentication tokens are used only to access the cloud provider you explicitly connect.</p>
    <p>When you use OneDrive, Microsoft Graph, WebDAV, Nextcloud, ownCloud, FTPS, or another connected provider, your requests also pass through those services and are subject to their respective terms and privacy policies.</p>
    <p>When you choose a DLNA/UPnP renderer, the app sends the selected audio stream and available playback metadata, such as title, artist, album, and artwork, to that renderer over your local network. For private or cloud media, the renderer may receive the audio through a temporary local proxy operated on your device. Aliox Player does not send your Microsoft access token or server password to the renderer. Only use DLNA/UPnP with devices and networks you trust.</p>

    <h2 id="data-deletion">6. Retention and Deletion</h2>
    <p>Aliox Player keeps local data only as long as needed for the app to function or while you keep your library configured.</p>
    <p>Aliox Player does not create or operate an Aliox user account. To delete all information stored by the app on your device, open <strong>Settings &gt; About &gt; Privacy &amp; data &gt; Delete all local app data</strong>. After you confirm, Android closes the app and deletes its private data, including:</p>
    <ul>
      <li>connected-provider credentials and tokens;</li>
      <li>the local library index, playlists, favorites, lyrics, playback information, queue information, and Private Top 10 Stats;</li>
      <li>cached artwork and other app caches;</li>
      <li>offline downloads stored in the app's private storage;</li>
      <li>app settings, permissions, and saved folder access.</li>
    </ul>
    <p>This action does <strong>not</strong> delete original audio files on your device, files stored in OneDrive or another connected server, manual backup files you exported to a folder you chose, or your Microsoft and server accounts. Those files and accounts must be managed directly with the device, storage provider, or server administrator.</p>
    <p>You can also disconnect a provider in the app. This removes that provider's locally stored credentials and tokens, sync state, synced library and playlist records, playback and queue references, app-managed offline copies, cached artwork, and related transient cache data. This is separate from the complete local-data deletion described above. Original files in the provider and the provider account itself are not deleted.</p>
    <p>Disconnecting OneDrive from Aliox Player removes the local connection and local OneDrive-derived data, but it does not revoke the consent previously granted to the app in your Microsoft account. To review or revoke that consent, use <a href="https://account.live.com/consent/Manage" rel="noopener noreferrer">Microsoft account consent management</a> for a personal account or <a href="https://myapps.microsoft.com" rel="noopener noreferrer">My Apps</a> for a work or school account. Your organization administrator may control consent for managed accounts.</p>
    <p>You may also clear the app's data from Android settings or uninstall the app. Manual backup files exported outside the app's private storage must be deleted separately from the folder where you saved them. For deletion assistance, contact <strong>alioxplayer@proton.me</strong>.</p>

    <h2>7. Security</h2>
    <p>The app stores cloud credentials in encrypted Android private app storage when supported by the Android version on your device. OneDrive and WebDAV account connections require HTTPS. FTPS encrypts FTP control and data connections with TLS and verifies the server hostname. Plain FTP is not supported. DLNA/UPnP playback and device control may use unencrypted HTTP on your local network because that is how many local media devices communicate. However, no method of digital transmission or storage is completely immune to risk.</p>

    <h2>8. Children</h2>
    <p>Aliox Player is not directed to children and does not knowingly collect children's data. If you believe a child has provided data to the app without appropriate consent, please contact us so we can help with removing local data.</p>

    <h2>9. Changes to This Policy</h2>
    <p>We may update this Privacy Policy to reflect changes in the app, supported providers, or legal requirements. The "Last Updated" date will change when the policy is revised.</p>

    <h2>10. Contact</h2>
    <p>If you have questions about this Privacy Policy, please contact <strong>alioxplayer@proton.me</strong> or open an issue on the project's official GitHub repository.</p>
  </main>
</body>
</html>
